# repo-a/mkdocs.yml
INHERIT: docs/_core/core.mkdocs.yml

# region Site
site_url: https://docs.singulargenomics.com/G4X-helpers/
site_description: Singular Genomics G4X data documentation site

repo_name: G4X-helpers
repo_url: https://github.com/Singular-Genomics/G4X-helpers

# region Nav
nav:
  - Docs Home: https://docs.singulargenomics.com

  - G4X-helpers:
    - index.md

    - Installation:
      - installation/index.md
      - Source install: installation/source.md
      - Docker setup: installation/docker.md

    - Usage:
      - usage/index.md

    - CLI features:
      - features/index.md
      - resegment: features/resegment.md
      - redemux: features/redemux.md
      - update_bin: features/update_bin.md
      - new_bin: features/new_bin.md
      - tar_viewer: features/tar_viewer.md
      - migrate: features/migrate.md

    - Contributing: contributing.md
    - Changelog: clog.md

  - G4X-viewer: https://docs.singulargenomics.com/G4X-viewer/

  - G4X-data: https://docs.singulargenomics.com/g4x_data/

  - G4X-tutorials: https://docs.singulargenomics.com/g4x_tutorials/
