name: Test Reusable Project Setup

on:
  push:   
  workflow_dispatch:

jobs:
  build-docs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v5

      - name: Setup Project Environment
        uses: ./.github/actions/setup-project.yml
        with:
          docs-submodule-token: ${{ secrets.CORE_DOCS_ASSETS_READ }}

      - name: run pytest
        run: |
          uv run pytest
